### ISSUE TITLE
Testing issue

### ISSUE THREAD

**Issue by Uceef94** [iprice/JSLBot#1]
This code works for me only when I delete the condition in the setup method [JSLBot.java (from line 163)]

>  if (argname.equals("arg0") || (!argname.equals("firstname"))) {
                System.out.println("===== FATAL ERROR =====");
                System.out.println("The name of the first method for setup() is "+argname);
                System.out.println("In the source this is called 'firstname'");
                System.out.println("JSLBot uses reflection to read parameter names to implement bot commands");
                System.out.println("It is necessary to include parameter names in the compiled bytecode");
                System.out.println("This is generally done by compiling (javac) with the '-g' and '-parameters' option to enable debug info");
                System.out.println("Command functionality will not work without this feature, the bot has been aborted for safety reasons");
                System.out.println("NetBeans note: Add to compiler additional options and DISABLE compile on save which ignores these settings");
                throw new AssertionError("Invalid JSLBot compilation, expected argument name 'newbrain', got '"+argname+"'");
            }

otherwise I get this error:

> ===== FATAL ERROR =====
The name of the first method for setup() is arg0
In the source this is called 'firstname'
JSLBot uses reflection to read parameter names to implement bot commands
It is necessary to include parameter names in the compiled bytecode
Exception in thread "main" java.lang.AssertionError: Invalid JSLBot compilation, expected argument name 'newbrain', got 'arg0'
This is generally done by compiling (javac) with the '-g' and '-parameters' option to enable debug info
Command functionality will not work without this feature, the bot has been aborted for safety reasons
NetBeans note: Add to compiler additional options and DISABLE compile on save which ignores these settings
	at JSLBot.JSLBot.setup(JSLBot.java:172)
	at JSLBot.JSLBot.loadConf(JSLBot.java:131)
	at JSLBot.JSLBot.<init>(JSLBot.java:119)
	at JSLBot.Test.main(Test.java:38)
D:\Users\X\Documents\NetBeansProjects\JSLBot\nbproject\build-impl.xml:1040: The following error occurred while executing this line:
D:\Users\X\Documents\NetBeansProjects\JSLBot\nbproject\build-impl.xml:805: Java returned: 1
BUILD FAILED (total time: 3 seconds)

Any Idea why?

**Comment by iprice** [comment]
You really should /read/ the message, it tells you exactly what its problem is and how to fix it, namely, when compiling it (javac) you need the -g and -parameters flag.

This is because the code exposes its "commands" (in the instant message interface) by using the names of the parameters to methods, without this all the instant message parameters become arg0 arg1 etc rather than retaining the name they were written with.

You can certainly start the bot by disabling this section, however you will find the instant message controls to be "complicated" by this, which is why it refuses to start.   If you're just using it as part of another package by driving it through Java API calls then this doesn't apply.

If you're unsure, I strongly recommend /against/ disabling this check and simply following the directions as given in the error message.

Alternatively download the precompiled JAR from the releases section as this already has the correct compilation flags attached to the build.

Thanks,
Iain

**Comment by iprice** [comment]
I will probably rework this requirement in a future version by simply adding my own annotations to each parameter rather than relying on Java Reflection alone to give me the names of parameters, which is what requires these debugging parameters to be passed.  But for now, this suffices.
